server:
  port: 9527

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    register-with-eureka: true #表示是否将自己注册进EurekaServer默认为true。
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:  # ↓↓↓↓  动态路由
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/**         # 断言，路径相匹配的进行路由
            - After=2023-11-08T10:25:21.671+08:00[Asia/Shanghai]
#            - Before=2023-11-08T10:25:21.671+08:00[Asia/Shanghai]
#            - Between=2023-11-08T10:07:21.671+08:00[Asia/Shanghai]
#            一个属性名称 一个正则表达式
            - Cookie=name,chenkang
#            一个属性名称 一个正则表达式
            - Header=X-Request-Id,\d+
#            - Host=**.baid.com,**.localhost:8080
#            - Method=GET #所有GET请求都将被路由
#            - Query=red, gree. #如果请求参数里包含red参数，并且值匹配为gree. 表达式，则将会被路由
#            - Query=green #如果请求包含green查询参数，则路由匹配。
          filters:
            - AddRequestHeader=AAFilter1, Filter1 # 添加请求头
            - AddRequestHeader=BBFilter2, Filter2 # 添加请求头

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/discovery/**      # 断言，路径相匹配的进行路由
#            - After=2023-11-08T10:25:21.671+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
      default-filters:
        - AddRequestHeader=AADefaultFilter1, default1
        - AddRequestHeader=BBDefaultFilter2, default2